# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47c9ca3e39124f27e6e561da80f24ed7731567b71e2e096632276aff1461739e943ea63d13b7bc434adbeadcf1159c514ad20132d463e3481ef48cb7b5f5905d

test:
  secret_key_base: f6cf251185386c9bbcf3d731c81907833e2a092e676ffbd3512fdbad277e073b8cfa839b3aaf2d71e4af8f0333bf6aac3eba095e5cbc8c53937f9f0687d473a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
